name: mobile
description: A new Flutter project.
publish_to: none
version: 1.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"  # tetap Dart 2 karena Flutter 3.7.11

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_local_notifications: ^9.7.0
  pin_input_text_field: ^4.1.1
  rxdart: ^0.26.0
   
  curved_navigation_bar: ^1.0.1
  http: ^0.13.4
  shimmer: ^2.0.0
  firebase_auth: ^1.1.3
  toast: ^0.1.5
  slide_popup_dialog: ^0.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.3
  url_launcher: ^6.1.5
  lazy_load_scrollview: ^1.0.1
  flutter_page_transition: ^0.1.0
  qr_flutter: ^4.1.0
  firebase_core: ^1.20.0
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^12.0.1
  blue_thermal_printer: ^1.2.3
  esc_pos_utils_plus: ^2.0.1+6
  esc_pos_bluetooth: ^0.4.1
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  flutter_image_compress: ^2.2.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.0+4
  share:
    git:
      url: https://github.com/creativefull/flutter_share.git
      ref: master
  package_info: ^2.0.2

  
  animated_bottom_navigation_bar: ^1.1.0 # alternatif animated_bottom_navigation_bar
  webview_flutter: ^3.0.0                # pengganti webview_flutter

  flutter_cache_manager: ^3.3.0
  pull_to_refresh_flutter3: ^2.0.1
  barcode_scan2: ^4.2.4
  screenshot: ^1.2.3
  marquee: ^2.2.3
  esys_flutter_share:
    git:
      url: https://github.com/cihadturhan/esys-flutter-share.git
      ref: nullsafety+embedding-2

  badges: ^2.0.2  # jangan upgrade ke 3.x jika tetap pakai Flutter 3.7.11

  lazy_load_refresh_indicator: ^2.0.0
  numeric_keyboard: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timeline_tile: ^2.0.0
  in_app_review: ^2.0.9
  app_links: ^2.1.0
  installed_apps: ^1.1.1
  flutter_custom_tabs:
  package_info_plus: ^2.0.0
  percent_indicator: ^4.0.0
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.1.0
  division: ^0.9.0
  nav: ^1.3.1
  flutter_screenutil: ^5.0.0
  grouped_list: ^5.1.2
  animations: ^2.0.0
  flutter_markdown: ^0.6.15
  camera: ^0.10.5+5
  path: ^1.8.0
  motion_tab_bar_v2: ^0.4.0
  image: ^3.0.1
  quickalert: ^1.0.2
  line_awesome_flutter: ^1.0.1
  dotted_line: ^3.0.0
  pin_code_fields: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  animated_bottom_navigation_bar: 1.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/img/sarinu/
    - assets/img/payuni2/
    - assets/img/funmo/
    - assets/img/kasir/
    - assets/img/paymobileku/
    - assets/img/outletpay/
    - assets/img/payku/
    - assets/img/ayoba/
    - assets/img/lariz/
    - assets/img/hexapay/
    - assets/img/hexamobile/
    - assets/img/centralbayar/
    - assets/img/violeta/
    - assets/img/shared/
    - assets/img/santren/

  fonts:
    - family: funmo
      fonts:
        - asset: fonts/funmo.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/roboto_mono.ttf
          weight: 100
        - asset: fonts/roboto_mono.ttf
          weight: 200
        - asset: fonts/roboto_mono.ttf
          weight: 300
        - asset: fonts/roboto_mono.ttf
          weight: 400
        - asset: fonts/roboto_mono.ttf
          weight: 500
        - asset: fonts/roboto_mono.ttf
          weight: 600
        - asset: fonts/roboto_mono.ttf
          weight: 700
        - asset: fonts/roboto_mono.ttf
          weight: 800
        - asset: fonts/roboto_mono.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf
          weight: 100
        - asset: fonts/montserrat.ttf
          weight: 200
        - asset: fonts/montserrat.ttf
          weight: 300
        - asset: fonts/montserrat.ttf
          weight: 400
        - asset: fonts/montserrat.ttf
          weight: 500
        - asset: fonts/montserrat.ttf
          weight: 600
        - asset: fonts/montserrat.ttf
          weight: 700
        - asset: fonts/montserrat.ttf
          weight: 800
        - asset: fonts/montserrat.ttf
          weight: 900
    - family: Nisebuschgardens
      fonts:
        - asset: fonts/Nisebuschgardens.ttf
    - family: Nunito
      fonts:
        - asset: fonts/NunitoBold.ttf
